import Head from "next/head";
import { useEffect } from "react";

export default function Login() {
  function open_signup() {
    const sign_in = document.getElementById("sign-in");
    const sign_up = document.getElementById("sign-up");
    document.getElementById("sign-in-els").style.display = "none";
    document.getElementById("sign-up-els").style.display = "block";
    sign_in.style.fontWeight = "normal";
    sign_up.style.fontWeight = "bold";
  }
  function open_signin() {
    const sign_in = document.getElementById("sign-in");
    const sign_up = document.getElementById("sign-up");
    sign_in.style.fontWeight = "bold";
    sign_up.style.fontWeight = "normal";
    document.getElementById("sign-in-els").style.display = "block";
    document.getElementById("sign-up-els").style.display = "none";
  }

  const signup = async (e) => {
    e.preventDefault();
    const password = document.getElementById("sign-up-password").value;
    const confirmpassword = document.getElementById(
      "sign-up-confirm-password"
    ).value;
    const username = document.getElementById("sign-up-username").value;
    const email = document.getElementById("sign-up-email").value;

    if (confirmpassword !== password) {
      alert("Passwords should match");
    }

    const data = { password, username, email };
    const res = await fetch("/auth/signup", {
      method: "POST",
      body: JSON.stringify(data),
      headers: {
        "Content-type": "application/json",
      },
    });
    console.log("status", res.status);
    let body = await res.json();
    if (res.status === 200) {
      localStorage.setItem("user", JSON.stringify(body));
      window.location.href = "/";
    } else {
      alert(`Error: ${body}`);
    }
  };

  const login = async (e) => {
    e.preventDefault();
    const password = document.getElementById("loginPassword").value;
    const email = document.getElementById("loginEmail").value;

    const data = { password, email };
    const res = await fetch("/auth/login", {
      method: "POST",
      body: JSON.stringify(data),
      headers: {
        "Content-type": "application/json",
      },
    });
    console.log("status", res.status);
    let body = await res.json();
    if (res.status === 200) {
      localStorage.setItem("user", JSON.stringify(body));
      window.location.href = "/";
    } else {
      alert(`Error: ${body}`);
    }
  };

  useEffect(() => {
    console.log("page is fully loaded");
    const userData = localStorage.getItem("user");
    if (userData) {
      window.location.href = "/";
    }
  }, []);

  return (
    <>
      <Head>
        <title>TWICHER | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="green-box">
          <div id="logo">
            <i className="fa fa-paw fa-2x" aria-hidden="true">
              {" "}
              TWICHER
            </i>
          </div>
        </div>
        <div className="gray-box"></div>
        <div className="wrapper">
          <div id="head-section">
            <div id="sign-in" onClick={open_signin}>
              SIGN IN
            </div>
            <div id="sign-up" onClick={open_signup}>
              SIGN UP
            </div>
            <div>
              <div id="sign-in-els">
                <form name="sign-in-form" onSubmit={login} id="signInForm">
                  <input
                    className="control"
                    id="loginEmail"
                    type="email"
                    name="sign-in-user"
                    placeholder="Email"
                  />
                  <br />
                  <input
                    className="control"
                    id="loginPassword"
                    type="password"
                    name="password"
                    placeholder="Password"
                  />
                  <br />
                  <button
                    type="submit"
                    id="loginButton"
                    className="submit-btn"
                    value="Sign in">
                    Sign in
                  </button>
                </form>
              </div>
              <div id="sign-up-els">
                <form name="sign-up-form" onSubmit={signup} id="myForm">
                  <input
                    className="control"
                    id="sign-up-email"
                    type="email"
                    name="email"
                    placeholder="Email"
                    required
                  />
                  <br />
                  <input
                    className="control"
                    id="sign-up-username"
                    type="text"
                    name="sign-up-user"
                    placeholder="Create username"
                    required
                  />
                  <input
                    className="control"
                    id="sign-up-password"
                    type="password"
                    name="create-pass"
                    placeholder="Create password"
                    required
                  />
                  <input
                    className="control"
                    id="sign-up-confirm-password"
                    type="password"
                    name="confirm-pass"
                    placeholder="Confirm password"
                    required
                  />
                  <br />
                  <button
                    id="signupButton"
                    type="submit"
                    className="submit-btn"
                    value="Sign up">
                    Register
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
